### PR TITLE
Lots of README cleanup

### PR DESCRIPTION
**Pull request by mikeatlas**
- Mac is the hardware name for Apple products running OS X, which the proper OS name. [Darwin](https://en.wikipedia.org/wiki/Darwin_%28operating_system%29), the core OS underneath OS X, is an [Apple-derived Mach-kernel plus various BSD components](https://en.wikipedia.org/wiki/History_of_OS_X), so I changed it to OS X where appropriate throughout.
- Consistency with parenthesis spacing in English prose (this) instead of ( that ).
- Fixed broken link markdown to author's blog posts.
- Changed instructions for OS X install via homebrew for unison pinned to 2.40, which is the (presently unpinned) version in the helper image of `gansbrest/fs-base`.
- Cleaned up sample `.hodorfile` with yaml markdown formatting.
- A little bit of grammar changes and fixes, although I tried to preserve the humor and ESL gentle mistakes, which are harmless, and, in my opinion, bring personality to this project, rather than making it read like all the other dull tech documentation.
- Added an **Unsupported** section

### CODE REVIEW

**Comment by mikeatlas** [comment]
Also, perhaps you might consider updating the project's GitHub description as well from "Boot2Docker VM ( Mac )" to just "Docker on OS X" to be more correct.

**Comment by gansbrest** [comment]
Ha, thanks a lot. It seem like there are some confilcts with master, could you pull master to your fork and resolve it, so it could be cleanly merged in.

As for description - we def can rename it into somth more meangingfull. "Docker on OS X" prob will not cut it, because Hodor is supported by both OS X and Linux. The goal is to provide consitent dev flow on Mac and Linux (no Windows yet), where if Linux is detected, it skips all Unison/VM/portMapping cruft and start using native volume mounting. I almost dailiy use Hodor for developent on Linux and I know people who use it for mixed Linux/OS X teams. I suggest we come up with somth that will reflect "process" crossplatform orientation. Thoughts?

**Comment by mikeatlas** [comment]
:+1: I totally support seamless usage of hodor across OS X and Linux... Just wanted to clarify that "Mac" is like calling Linux "Dell" or "HP", even though technically OS X is only supposed to run on Apple Mac computers.

Anyhoo, here's the merge fix.

**Comment by mikeatlas** [comment]
Great :))

**Comment by gansbrest** [comment]
Thank you! I updated description a bit to remove Mac :) I wonder what changed in new Unison version?

**Pull request merged**
