### PR TITLE
env_file option

### PR DESCRIPTION
**Pull request by mjroeleveld**
Just as Docker Compose, this gives you the option to specify environment variables in a file. This is handy for situations where you want to push your `.hodorfile`, but like to keep (some) environment variables private and untracked.

### CODE REVIEW

**Comment by gansbrest** [comment]
Could you give more concrete example of this?

.hodorfile is already processed through ERB, so you can have things like:

````
    environment:
      AWS_ACCESS_KEY_ID: <%= ENV['AWS_ACCESS_KEY_ID'] %>
      AWS_SECRET_ACCESS_KEY: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
````

note that you don't actually store actual values here.

I think external file could be useful if you have lots of ENV vars and you don't want to clobber .hodorfile. But not sure if that's the case for dev as both env file and .hodorfile will need to be commited for the project.

Did I miss something here?

**Comment by joachimroeleveld** [comment]
Well, in many of my current projects I load environment variables such as session secrets, api keys, credentials etc. from a file called `env.yml` or `env.json`. I then create a file called `env.sample.yml` for other collaborators for cases when they would run the app on their own machine. Build tools have plugins (example: `grunt-contrib-env`) that load these files and set the environment variables at runtime. This way, you don't have to check private environment variables in git, but you do have a persistent way of keeping them between reboots. This workflow is also described in various blogposts, such as [this](http://himanshu.gilani.info/blog/2012/09/26/bootstraping-a-node-dot-js-app-for-dev-slash-prod-environment/) one

**Comment by joachimroeleveld** [comment]
By the way, I'm sorry for the 'removed trailing spaces changes'. My editor automatically removes these, and I didn't think of removing these lines from my commits.

**Comment by gansbrest** [comment]
In the blog post that you sent hey have this in env.json:

```
{
  "development": {
      "facebook_app_id": "facebook_dummy_dev_app_id",
      "facebook_app_secret": "facebook_dummy_dev_app_secret",
  }, 
  "production": {
      "facebook_app_id": "facebook_dummy_prod_app_id",
      "facebook_app_secret": "facebook_dummy_prod_app_secret",
  }
````

Seem like some internal app switches based on NODE_ENV variable. So in their case they probably commit all those settings for every environment which is not very ideal/secure I guess.

Do you do it differently? Like when you do development your env.yml contains only local settings and when you deploy, you subsitute env.yml with production values?

Could you paste your file env.yml so I could understand if it's project switches, or env varibables and how it relates to Docker containers&

**Comment by joachimroeleveld** [comment]
Yes, I do it as you state in your second remark. 

This is my `env.sample.yml` (tracked in git):

	SESSION_SECRET: session_secret
	API_CLIENT_ID: client_id
	API_CLIENT_SECRET: client_secret

When I clone the repository I copy `env.sample.yml` to `env.yml` (*not* tracked in git) and edit the placeholder values to the actual values. My `.hodorfile` in the meantime, looks like this:

	...
	containers:
	  test-container:
	    ...
	    environment: (non-private environment variables)
	      NODE_ENV: <%= ENV['NODE_ENV'] %>
	      PORT: <%= ENV['PORT'] %>
	    env_file: "env.yml"
	    ...
	...

which I track in git.

When I deploy my application to production, I enter the same environment variables (but with propably different values since they may vary for production) in the application configuration.

I found this to be the most convenient way to pass private environment variables to my application runtime environment while keeping them out of git. Do you do this much differently?

**Pull request closed without merging**
